name: 'Deploy Exchange Lab'

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #- name: Login to Azure
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
#
    #- name: Detach Azure Disk
    #  run: |
    #    az vm disk detach \
    #      --name ex01-osdisk \
    #      --resource-group ExchangeLab \
    #      --vm-name EX01
    #
    #- name: Delete Azure Disk
    #  run: |
    #    az disk delete \
    #      --name ex01-osdisk \
    #      --resource-group ExchangeLab \
    #      --yes \
    #      --no-wait
#
    #- name: Logout of Azure
    #  run: az logout      

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Initialize
      run: terraform init

    #- name: Terraform Destroy
    #  run: terraform destroy -auto-approve

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Deploy Exchange Server
      run: |
        terraform apply -var="create_exchange=true" -auto-approve

    - name: Assign Custom DNS to VNet
      run: |
        terraform apply -var="custom_dns=10.1.0.4" -auto-approve

    #- name: Reboot Servers
    #  run: |
    #    az login
    #    az vm restart -g ExchangeLab -n DC01
    #    az vm restart -g ExchangeLab -n EX01

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
